language: generic 

sudo: required
services:
  - docker
  
before_install:
  - docker build -t sri554278/multi-docker -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true sri554278/multi-docker npm run test

after_success:
  - docker build -t sri554278/multi-docker-client ./client
  - docker build -t sri554278/multi-docker-nginx ./nginx
  - docker build -t sri554278/multi-docker-server ./server
  - docker build -t sri554278/multi-docker-worker ./worker
  # Login to DockerHub
  #- docker login -u $DOCKER_HUB_USERID -p $DOCKER_HUB_PWD -e $DOCKER_HUB_EMAIL
  - echo "DOCKER_HUB_PWD" | docker login -u $DOCKER_HUB_USERID --password-stdin
  # Push prod images to Docker HUB
  - docker push $DOCKER_HUB_USERID/multi-docker-client
  - docker push $DOCKER_HUB_USERID/multi-docker-nginx
  - docker push $DOCKER_HUB_USERID/multi-docker-server
  - docker push $DOCKER_HUB_USERID/multi-docker-worker
    