version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  
  redis:
    image: 'redis:latest'
  
  nginx:
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
      - client  
    ports:
     - '3050:80'
     
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    # Below to fix issue with exit code 0 in windows
    stdin_open: true
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    # Below to fix issue with exit code 0 in windows
    stdin_open: true
      
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    # Below to fix issue with exit code 0 in windows
    stdin_open: true
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
